/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const legacySidebars = require('./sidebars.js');

const stripNumberPrefix = (label) =>
  label.replace(/^\d+(?:[A-F])?(?:\s*[–-]\s*\d+)?\s*·\s*/, '');

const typescriptDocLabels = {
  'typescript/01-05-foundations-to-unions': 'Foundations → Unions & Intersections',
  'typescript/06-10-narrowing-functions-safety-literals': 'Narrowing → Literals / as const / satisfies',
  'typescript/11-16-generics-and-type-manipulation': 'Generics & Type Manipulation',
  'typescript/17-25-classes-compatibility-inference-nullability-functions': 'Classes, Compatibility, Variance, Inference & Advanced Functions',
  'typescript/26-31-modules-tsconfig-monorepos-declarations-libraries-js': 'Modules, TSConfig, Monorepos, Declarations & Libraries',
  'typescript/32-39-runtime-validation-errors-async-decorators-jsx-react-node': 'Runtime Validation, Errors, Async, Decorators, JSX, React & Node',
  'typescript/40-49-backends-architecture-domain-type-level-compiler-performance-debugging': 'Backends, Architecture, Domain, Type-Level, Compiler, Performance & Debugging',
  'typescript/50-59-testing-linting-build-security-production-migration-patterns-staff': 'Testing, Linting, Build, Security, Production, Migration & Staff Architecture',
};

const cleanItem = (item) => {
  if (typeof item === 'string') {
    const label = typescriptDocLabels[item];
    return label ? {type: 'doc', id: item, label} : item;
  }
  if (!item || typeof item !== 'object') return item;

  if (item.type === 'category') {
    return {
      ...item,
      label: stripNumberPrefix(item.label),
      items: item.items.map(cleanItem),
    };
  }

  return item;
};

const cleanItems = (items) => items.map(cleanItem);
const handbookRoot = legacySidebars.handbookSidebar;

const reactItems = handbookRoot[0].items;
const nextjsItems = handbookRoot[1].items;
const typescriptItems = handbookRoot[2].items;

const generated = (dirName) => [{type: 'autogenerated', dirName}];

module.exports = {
  reactSidebar: cleanItems(reactItems),
  nextjsSidebar: cleanItems(nextjsItems),
  typescriptSidebar: cleanItems(typescriptItems),
  javascriptSidebar: generated('javascript'),
  nodejsSidebar: generated('nodejs'),
  databasesSidebar: generated('databases'),
  systemDesignSidebar: generated('system-design'),
  devopsSidebar: generated('devops'),
  wordpressSidebar: generated('wordpress'),
  aiEngineeringSidebar: generated('ai-engineering'),
};