/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const legacySidebars = require('./sidebars.js');

const stripNumberPrefix = (label) =>
  label.replace(/^\d+(?:[A-F])?(?:\s*[–-]\s*\d+)?\s*·\s*/, '');

const cleanItem = (item) => {
  if (typeof item === 'string') return item;
  if (!item || typeof item !== 'object') return item;

  if (item.type === 'category') {
    return {
      ...item,
      label: stripNumberPrefix(item.label),
      items: item.items.map(cleanItem),
    };
  }

  return item;
};

const cleanItems = (items) => items.map(cleanItem);
const handbookRoot = legacySidebars.handbookSidebar;

const reactItems = handbookRoot[0].items;
const nextjsItems = handbookRoot[1].items;
const typescriptItems = handbookRoot[2].items;

const generated = (dirName) => [{ type: 'autogenerated', dirName }];

module.exports = {
  reactSidebar: cleanItems(reactItems),
  nextjsSidebar: cleanItems(nextjsItems),
  typescriptSidebar: cleanItems(typescriptItems),
  javascriptSidebar: generated('javascript'),
  nodejsSidebar: generated('nodejs'),
  databasesSidebar: generated('databases'),
  systemDesignSidebar: generated('system-design'),
  devopsSidebar: generated('devops'),
  wordpressSidebar: generated('wordpress'),
  aiEngineeringSidebar: generated('ai-engineering'),
};
