export const CATEGORY_DESCRIPTIONS = {
  "Start Here": "the mental models, expectations, and learning sequence that make later TypeScript topics easier to reason about",
  "Setup and Tooling": "installing, running, configuring, and debugging the TypeScript toolchain",
  "Compiler Fundamentals": "how TypeScript parses source, builds symbols, checks types, reports diagnostics, and optionally emits output",
  "JavaScript Foundations for TypeScript": "the JavaScript runtime behavior that TypeScript models rather than replaces",
  "Type System Foundations": "the relationships TypeScript uses to infer, compare, narrow, and assign types",
  "Primitive Types": "the TypeScript representations of JavaScript primitive values and special control-flow types",
  "Literal Types": "types that represent exact values and preserve domain-specific information",
  "Variables and Inference": "how declarations, mutability, annotations, and widening influence inferred types",
  "Arrays and Tuples": "typed ordered collections, fixed-position records, and variadic argument lists",
  "Object Types": "structural descriptions of object properties, keys, mutability, and exactness limitations",
  "Functions": "typing callable behavior, parameters, returns, callbacks, overloads, generics, and variance",
  "Union and Intersection Types": "combining alternatives and constraints to model domain variants safely",
  "Type Narrowing": "using runtime evidence and control flow to refine broad static types",
  "Type Aliases and Interfaces": "naming, extending, composing, and publishing reusable structural contracts",
  "Enums and Alternatives": "runtime enum objects and lighter JavaScript-first ways to represent finite choices",
  "Classes": "typing JavaScript classes, construction, inheritance, visibility, and instance behavior",
  "Generics": "preserving relationships between input and output types without giving up reuse",
  "keyof and Indexed Access": "deriving keys and property types from existing object and tuple types",
  "typeof and Value-to-Type Patterns": "deriving static types from runtime declarations to maintain one source of truth",
  "Mapped Types": "systematically transforming every property in an object-like type",
  "Conditional Types": "selecting types according to assignability relationships",
  "infer Keyword": "extracting component types from larger type patterns inside conditional types",
  "Template Literal Types": "building and parsing string-shaped types from literal unions",
  "Utility Types": "standard reusable type transformations included with TypeScript",
  "Type Assertions": "overriding the checker when the programmer has evidence it cannot derive",
  "satisfies Operator": "checking a value against a contract while preserving its useful inferred type",
  "Null and Undefined": "modeling absence explicitly under strict null checking",
  "Error Handling": "representing thrown errors and expected failure paths without losing safety",
  "Async TypeScript": "typing promises, concurrency, cancellation, and asynchronous iteration",
  "Iterators and Generators": "typing pull-based sequences and functions that pause and resume",
  "Modules": "aligning TypeScript imports and exports with the runtime and build tool",
  "Declaration Files": "describing JavaScript APIs for the checker without emitting runtime code",
  "Libraries and Type Definitions": "selecting, resolving, and publishing platform and package type declarations",
  "tsconfig.json": "defining the compiler program, runtime assumptions, emit policy, and project boundaries",
  "Strictness Options": "turning uncertain JavaScript behavior into explicit, actionable diagnostics",
  "Project References": "splitting large repositories into independently buildable typed projects",
  "TypeScript with Node.js": "matching TypeScript configuration and types to modern Node.js runtime semantics",
  "TypeScript with React": "typing components, hooks, events, refs, and reusable component APIs",
  "TypeScript with Vue": "typing Vue macros, templates, composables, state, and generic components",
  "Runtime Validation": "converting untrusted runtime data into validated values with trustworthy static types",
  "API Design": "designing stable request, response, error, pagination, and generated contracts",
  "Database Types": "separating storage records, domain models, commands, and public DTOs",
  "Advanced Type Patterns": "encoding stronger domain invariants with reusable type-level patterns",
  "Variance": "understanding how subtyping behaves through generic containers and callable parameters",
  "Type-Level Programming": "treating types as compile-time transformations while managing complexity limits",
  "Library Authoring": "shipping stable public types, declarations, module formats, and package metadata",
  "Type Testing": "testing which programs should compile and which should be rejected",
  "Testing TypeScript Applications": "keeping runtime tests strongly typed without unsafe casts",
  "ESLint and Code Quality": "using type-aware lint rules to catch risky behavior beyond compiler diagnostics",
  "Migration from JavaScript": "introducing TypeScript incrementally without stopping feature delivery",
  "Performance": "measuring and reducing checker, editor, declaration, and build costs",
  "Security": "keeping static types from becoming false trust at runtime security boundaries",
  "Architecture": "placing types at clear ownership and dependency boundaries in large systems",
  "Production Engineering": "operating TypeScript safely through CI, builds, monitoring, upgrades, and rollback",
  "Common TypeScript Mistakes": "recognizing patterns that weaken safety or make types harder to maintain",
  "Projects": "integrating multiple TypeScript skills into deliverable software",
  "Exercises": "building fluency through increasingly realistic type and production problems",
  "Interview Preparation": "explaining TypeScript clearly, debugging unfamiliar types, and making architecture trade-offs",
  "Reference and Audits": "quick lookup material, official sources, compatibility notes, and completeness evidence"
};

export const DEFINITIONS = {
  'Type Inference': 'Type inference lets the checker derive a useful type from declarations, expressions, contextual expectations, and control flow.',
  'Structural Typing': 'Structural typing compares members and call signatures rather than requiring matching declaration names.',
  Assignability: "Assignability is TypeScript's practical relation for deciding whether a source value may be used at a target type.",
  Widening: 'Widening replaces an exact literal type with a broader mutable type when the value may later change.',
  Narrowing: 'Narrowing uses runtime checks and control flow to reduce a union to the cases still possible.',
  'Type Erasure': 'Type erasure means most TypeScript-only syntax is removed before JavaScript executes.',
  'Compilation Pipeline': 'The compiler parses source, binds symbols, checks types, reports diagnostics, and optionally emits JavaScript or declarations.',
  'Module Resolution': 'Module resolution maps an import specifier to runtime files and declarations according to the selected environment.',
  'Runtime Validation': 'Runtime validation checks actual values and converts valid input into a trusted domain shape.',
  'What satisfies Does': "The satisfies operator checks compatibility without replacing the expression's useful inferred type.",
};

export const OFFICIAL = {
  Modules: [['TypeScript modules', 'https://www.typescriptlang.org/docs/handbook/modules/reference.html'], ['Node.js packages', 'https://nodejs.org/api/packages.html']],
  'tsconfig.json': [['TSConfig reference', 'https://www.typescriptlang.org/tsconfig/']],
  'Strictness Options': [['TSConfig reference', 'https://www.typescriptlang.org/tsconfig/']],
  'Project References': [['Project references', 'https://www.typescriptlang.org/docs/handbook/project-references.html']],
  'TypeScript with Node.js': [['Node.js TypeScript', 'https://nodejs.org/api/typescript.html']],
  'TypeScript with React': [['React and TypeScript', 'https://react.dev/learn/typescript']],
  'TypeScript with Vue': [['Vue and TypeScript', 'https://vuejs.org/guide/typescript/overview.html']],
  'Runtime Validation': [['Zod', 'https://zod.dev/']],
  'ESLint and Code Quality': [['typescript-eslint typed linting', 'https://typescript-eslint.io/getting-started/typed-linting/']],
};
